spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@db20220712201125_high?TNS_ADMIN=/Song/Oracle/Wallet_DB20220712201125
        username: admin
        password: Choco025874!

